### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by 21emerald** [xuqingfeng/caddy-rate-limit#8]
A runtime error throw while I am using caddy with ratelimit plugin in docker. I have no idea about these errors, and seems that it was ratelimit error destroyed the running caddy.

```log
2017-02-18T03:14:23.709030693Z fatal error: concurrent map read and map write
2017-02-18T03:14:23.712128369Z 
2017-02-18T03:14:23.712160518Z goroutine 697997 [running]:
2017-02-18T03:14:23.712168803Z runtime.throw(0xa7e28b, 0x21)
2017-02-18T03:14:23.712175464Z  /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4203a71f0 sp=0xc4203a71d0
2017-02-18T03:14:23.712184232Z runtime.mapaccess2_faststr(0x9c7220, 0xc42000dc50, 0xc4203d21b0, 0xf, 0x1, 0xc4203d21b0)
2017-02-18T03:14:23.712196490Z  /usr/local/go/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc4203a7250 sp=0xc4203a71f0
2017-02-18T03:14:23.712209585Z github.com/xuqingfeng/caddy-rate-limit.(*CaddyLimiter).AllowN(0xc420026068, 0xc4202e4300, 0x2, 0x2, 0x64, 0x96, 0xc42023e0d0, 0x1, 0x1, 0xc4201a02b0, ...)
2017-02-18T03:14:23.712221605Z  /home/caddy/go/src/github.com/xuqingfeng/caddy-rate-limit/caddylimiter.go:30 +0xb3 fp=0xc4203a7378 sp=0xc4203a7250
2017-02-18T03:14:23.712231405Z github.com/xuqingfeng/caddy-rate-limit.(*CaddyLimiter).Allow(0xc420026068, 0xc4202e4300, 0x2, 0x2, 0x64, 0x96, 0xc42023e0d0, 0x1, 0x1, 0xc4201a02b0, ...)
2017-02-18T03:14:23.712239102Z  /home/caddy/go/src/github.com/xuqingfeng/caddy-rate-limit/caddylimiter.go:24 +0x8c fp=0xc4203a73f0 sp=0xc4203a7378
2017-02-18T03:14:23.712251834Z github.com/xuqingfeng/caddy-rate-limit.RateLimit.ServeHTTP(0xd20e20, 0xc420229290, 0xc420222880, 0x1, 0x1, 0xd255a0, 0xc42059e7e0, 0xc42047e870, 0x750390, 0xc4203a75c0, ...)
2017-02-18T03:14:23.712608489Z  /home/caddy/go/src/github.com/xuqingfeng/caddy-rate-limit/ratelimit.go:65 +0x35a fp=0xc4203a7558 sp=0xc4203a73f0
2017-02-18T03:14:23.712646338Z github.com/xuqingfeng/caddy-rate-limit.(*RateLimit).ServeHTTP(0xc4202292c0, 0xd255a0, 0xc42059e7e0, 0xc42047e870, 0x0, 0x0, 0xc420228c90)
2017-02-18T03:14:23.712655732Z  <autogenerated>:1 +0x8f fp=0xc4203a75c0 sp=0xc4203a7558
2017-02-18T03:14:23.712665281Z github.com/mholt/caddy/caddyhttp/errors.ErrorHandler.ServeHTTP(0xd20fe0, 0xc4202292c0, 0x0, 0x0, 0xc420228c90, 0x0, 0x0, 0xc420237270, 0x0, 0x0, ...)
2017-02-18T03:14:23.712672907Z  /tmp/custombuild_8338_503942783/src/github.com/mholt/caddy/caddyhttp/errors/errors.go:40 +0x129 fp=0xc4203a7710 sp=0xc4203a75c0
2017-02-18T03:14:23.712680058Z github.com/mholt/caddy/caddyhttp/errors.(*ErrorHandler).ServeHTTP(0xc4201a70e0, 0xd255a0, 0xc42059e7e0, 0xc42047e870, 0x0, 0x40efee, 0xc4201b0840)
2017-02-18T03:14:23.712686997Z  <autogenerated>:1 +0xb0 fp=0xc4203a77a8 sp=0xc4203a7710
2017-02-18T03:14:23.712697108Z github.com/mholt/caddy/caddyhttp/header.Headers.ServeHTTP(0xd1e3a0, 0xc4201a70e0, 0xc420228bd0, 0x2, 0x2, 0xd25520, 0xc42059e750, 0xc42047e870, 0xa30280, 0xc4203a7901, ...)
```

**Comment by xuqingfeng** [comment]
Sorry for the delay(didn't see the notification).

Can you show me the `Dockerfile` so I can reproduce this issue?

**Comment by 21emerald** [comment]
Ok. `Dockerfile` here.
```dockerfile
# ARG plugins=ratelimit

RUN apk add --no-cache openssh-client tar curl

# install caddy
RUN curl --silent --show-error --fail --location \
      --header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" -o - \
      "https://caddyserver.com/download/build?os=linux&arch=amd64" \
    | tar --no-same-owner -C /usr/bin/ -xz caddy \
 && chmod 0755 /usr/bin/caddy \ 
 && /usr/bin/caddy -version

EXPOSE 80 443 2015
WORKDIR /srv

COPY Caddyfile /etc/Caddyfile

ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile", "--log", "/var/log/caddy"]
```

And here is part of `Caddyfile`.
```
xxx.xx {
  gzip
  ratelimit /selection 5 10 second
  ratelimit /services/push 100 120 minute
  ratelimit / 250 400 minute
}
```

**Comment by xuqingfeng** [comment]
@21emerald

I committed a fix, if you want to test you can build caddy from source according to https://github.com/mholt/caddy/issues/1341#issuecomment-271672886

Thanks for file this issue.
